version: "3.8"
services:
  mongodb:
    hostname: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  westsea-traceability:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
